### ISSUE TITLE
Upload Photo

### ISSUE THREAD

**Issue by ruslanraupoff** [blowstack/ckeditor-nuxt#12]
![image](https://user-images.githubusercontent.com/16702915/106030354-e9bf2300-60ef-11eb-85c4-ea176704d0ae.png)
How to fix it?

**Comment by blowstack** [comment]
Where this come from? Send more details. Some code maybe...

**Comment by ruslanraupoff** [comment]
![image](https://user-images.githubusercontent.com/16702915/106640812-516de600-65a8-11eb-9654-af2331b4e9ac.png)
![image](https://user-images.githubusercontent.com/16702915/106640925-73ffff00-65a8-11eb-9f7a-f169858c3132.png)

**Comment by awunder** [comment]
the q is, what does ckeditor expect as return? just the image url? or an object? with what attribute name?

**Comment by awunder** [comment]
never mind.. https://github.com/blowstack/ckeditor-nuxt/issues/11#issuecomment-750448073

**Comment by blowstack** [comment]
@rusanraupoff you probably have to return this on your backend:
``
return {"url": your_image_url}
``

I will update the Readme related to img soon.

**Comment by ruslanraupoff** [comment]
Is not send request to server
