### ISSUE TITLE
How to add Markdown Plugin and use Balloon editor

### ISSUE THREAD

**Issue by alamyudi** [blowstack/ckeditor-nuxt#5]
Hi, thanks for creating this component. I was wondering how to add Markdown plugin and use Balloon editor ?

**Comment by blowstack** [comment]
Hi, to use Markdown and Balloon editor you will have to make your own custom build for nuxt. You can follow related posts I wrote. First I recommend to start with [how to add ckeditor to nuxt](https://blowstack.com/blog/frameworks/ckeditor-5-nuxt-integration) and then try [how to create a custom build for ckeditor](https://blowstack.com/blog/frameworks/create-ckeditor-5-custom-build).
