### ISSUE TITLE
Make simple upload accept returning link to image

### ISSUE THREAD

**Issue by uncikmarek** [blowstack/ckeditor-nuxt#6]
Hi, Im looking for way to not use base64, right now my upload works well, image saves to server but I cant figure out how to return a image url in json, I tried some names for returning property but got no luck, but then I noticed that image is there but not showing and its src is base64, so my question is If I can somehow set image src to be a link instead of base64, thanks in advance

**Comment by blowstack** [comment]
Hi, I think it's rather related to your backend not the nuxt component itself. It's totally possible to get simple url after upload, I have such implementation. What a framework backend do you use? Maybe I will be able to help.

**Comment by uncikmarek** [comment]
Thanks for answer, Iam using adonis.js v4 here is my function in FilesController:
```javascript
async imageUpload ({ auth, request }) {
        const image = request.file('upload', {
            types: ['image'],
            size: '10mb'
        })
        const ext = image.extname
        const fileName = await str_random(20) + "." + ext

        await image.move(Helpers.publicPath('uploads'), {
            name: fileName,
            overwrite: true,
        })

        if (!image.moved()) {
            return image.error()
        }
        return {
            success: true,
            file:  Config.get('app.url') + '/uploads/' + fileName
        }
    }
```

So I return a src link to image on server in property file, but after upload when I check html element of image in ck, its src is base64 hash, I want it to be this link

**Comment by blowstack** [comment]
Try to change file property in return into url. This should do the trick.

```javascript
return {
   success: true,
   url:  Config.get('app.url') + '/uploads/' + fileName
}
```

**Comment by uncikmarek** [comment]
@blowstack thank you, it works now, altough I'am almost 100% sure that Ive already tried to use url, but nevermind =)
